// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  foundrySkillSidebar: [
    { type: 'doc', id: 'azure-ai-foundry/overview', label: 'Track Overview' },
    { type: 'doc', id: 'azure-ai-foundry/prerequisites', label: 'Prerequisites & Setup' },
    {
      type: 'category',
      label: 'Platform & Architecture',
      items: [{ type: 'autogenerated', dirName: 'azure-ai-foundry/01-platform' }],
    },
    {
      type: 'category',
      label: 'Agent Service & Types',
      items: [{ type: 'autogenerated', dirName: 'azure-ai-foundry/02-agent-service' }],
    },
    { type: 'doc', id: 'azure-ai-foundry/cheat-sheet', label: 'CLI & SDK Cheat Sheet' },
  ],

  responsibleAiSidebar: [
    { type: 'doc', id: 'responsible-ai/overview', label: 'Track Overview' },
    {
      type: 'category',
      label: 'RAI Standard & Governance',
      items: [{ type: 'autogenerated', dirName: 'responsible-ai/01-rai-standard' }],
    },
    {
      type: 'category',
      label: 'Purview AI Hub & Shadow AI',
      items: [{ type: 'autogenerated', dirName: 'responsible-ai/02-purview-ai-hub' }],
    },
    {
      type: 'category',
      label: 'Fairness & Bias Mitigation',
      items: [{ type: 'autogenerated', dirName: 'responsible-ai/03-content-safety' }],
    },
  ],

  ai102Sidebar: [
    { type: 'doc', id: 'ai-102/overview', label: 'Exam Overview' },
  ],

  az305Sidebar: [
    { type: 'doc', id: 'az-305/overview', label: 'Exam Overview' },
  ],

  sc500Sidebar: [
    { type: 'doc', id: 'sc-500/overview', label: 'Exam Overview' },
  ],

  az104Sidebar: [
    { type: 'doc', id: 'az-104/overview', label: 'Exam Overview' },
  ],

  az700Sidebar: [
    { type: 'doc', id: 'az-700/overview', label: 'Exam Overview' },
  ],
};

export default sidebars;
