// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  foundrySkillSidebar: [
    { type: 'doc', id: 'azure-ai-foundry/overview', label: 'Track Overview' },
    { type: 'doc', id: 'azure-ai-foundry/prerequisites', label: 'Prerequisites & Setup' },
    {
      type: 'category',
      label: 'Platform & Architecture',
      items: [{ type: 'autogenerated', dirName: 'azure-ai-foundry/01-platform' }],
    },
    {
      type: 'category',
      label: 'Agent Service & Types',
      items: [{ type: 'autogenerated', dirName: 'azure-ai-foundry/02-agent-service' }],
    },
    {
      type: 'category',
      label: 'Hosted Agents',
      items: [{ type: 'autogenerated', dirName: 'azure-ai-foundry/03-hosted-agents' }],
    },
    {
      type: 'category',
      label: 'Observability & Evaluation',
      items: [{ type: 'autogenerated', dirName: 'azure-ai-foundry/04-observability' }],
    },
    {
      type: 'category',
      label: 'Multi-Agent Orchestration',
      items: [{ type: 'autogenerated', dirName: 'azure-ai-foundry/05-multi-agent' }],
    },
    { type: 'doc', id: 'azure-ai-foundry/cheat-sheet', label: 'CLI & SDK Cheat Sheet' },
  ],

  responsibleAiSidebar: [
    { type: 'doc', id: 'responsible-ai/overview', label: 'Track Overview' },
    {
      type: 'category',
      label: 'RAI Standard & Governance',
      items: [{ type: 'autogenerated', dirName: 'responsible-ai/01-rai-standard' }],
    },
    {
      type: 'category',
      label: 'Purview AI Hub & Shadow AI',
      items: [{ type: 'autogenerated', dirName: 'responsible-ai/02-purview-ai-hub' }],
    },
    {
      type: 'category',
      label: 'Fairness & Bias Mitigation',
      items: [{ type: 'autogenerated', dirName: 'responsible-ai/03-content-safety' }],
    },
  ],

  ai102Sidebar: [
    { type: 'doc', id: 'ai-102/overview', label: 'Exam Overview' },
  ],

  az305Sidebar: [
    { type: 'doc', id: 'az-305/overview', label: 'Exam Overview' },
  ],

  sc500Sidebar: [
    { type: 'doc', id: 'sc-500/overview', label: 'Exam Overview' },
  ],

  az104Sidebar: [
    { type: 'doc', id: 'az-104/overview', label: 'Exam Overview' },
  ],

  az700Sidebar: [
    { type: 'doc', id: 'az-700/overview', label: 'Exam Overview' },
  ],

  agenticReliabilitySidebar: [
    { type: 'doc', id: 'agentic-reliability/overview', label: 'Track Overview' },
    {
      type: 'category',
      label: 'The Hallucination Audit',
      items: [{ type: 'autogenerated', dirName: 'agentic-reliability/01-hallucination-audit' }],
    },
    {
      type: 'category',
      label: 'Context Rot at Scale',
      items: [{ type: 'autogenerated', dirName: 'agentic-reliability/02-context-rot' }],
    },
    {
      type: 'category',
      label: 'The Verifiable Orchestrator',
      items: [{ type: 'autogenerated', dirName: 'agentic-reliability/03-verifiable-orchestrator' }],
    },
    {
      type: 'category',
      label: 'Semantic Control',
      items: [{ type: 'autogenerated', dirName: 'agentic-reliability/04-semantic-control' }],
    },
  ],

  aiArchitectureRaiSidebar: [
    { type: 'doc', id: 'ai-architecture-rai/overview', label: 'Track Overview' },
    { type: 'doc', id: 'ai-architecture-rai/week-01', label: 'Week 1: RAI Foundations for Architects' },
    { type: 'doc', id: 'ai-architecture-rai/week-02', label: 'Week 2: Architecture Patterns + RAI by Design' },
    { type: 'doc', id: 'ai-architecture-rai/week-03', label: 'Week 3: Microsoft Stack Deep Dive' },
    { type: 'doc', id: 'ai-architecture-rai/week-04', label: 'Week 4: Applied Design + Review Practice' },
  ],

  claudeArchitectSidebar: [
    { type: 'doc', id: 'claude-architect/overview', label: 'Exam Overview & Study Plan' },
  ],

  resourcesSidebar: [
    { type: 'doc', id: 'resources/overview', label: 'Resources Hub' },
    { type: 'doc', id: 'resources/tools', label: '🛠️ Tools' },
    { type: 'doc', id: 'resources/articles', label: '📰 Articles' },
    { type: 'doc', id: 'resources/learning', label: '📚 Learning' },
  ],

  learningPlanSidebar: [
    { type: 'doc', id: 'learning-plan/overview', label: '🎯 Plan Overview' },
    { type: 'doc', id: 'learning-plan/sources-and-verification', label: '✅ Fuentes y Verificación' },
    { type: 'doc', id: 'learning-plan/methodology-best-practices', label: '🧭 Metodología y Mejores Prácticas' },
    {
      type: 'category',
      label: 'Fase 1: Fundamentos (Semanas 1-4)',
      items: [{ type: 'autogenerated', dirName: 'learning-plan/01-foundation' }],
    },
    {
      type: 'category',
      label: 'Fase 2: Datos & Automatización (Semanas 5-8)',
      items: [{ type: 'autogenerated', dirName: 'learning-plan/02-data-automation' }],
    },
    {
      type: 'category',
      label: 'Fase 3: Ciberseguridad (Semanas 9-12)',
      items: [{ type: 'autogenerated', dirName: 'learning-plan/03-cybersecurity' }],
    },
    {
      type: 'category',
      label: 'Fase 4: AI para Negocios (Semanas 13-20)',
      items: [{ type: 'autogenerated', dirName: 'learning-plan/04-ai-business' }],
    },
    {
      type: 'category',
      label: 'Fase 5: Cloud + AI (Semanas 21-28)',
      items: [{ type: 'autogenerated', dirName: 'learning-plan/05-cloud-ai' }],
    },
    {
      type: 'category',
      label: 'Fase 6: Lanzamiento (Semanas 29-36)',
      items: [{ type: 'autogenerated', dirName: 'learning-plan/06-career-launch' }],
    },
    {
      type: 'category',
      label: '🧪 Retos: Seguridad de IA Aplicada',
      items: [{ type: 'autogenerated', dirName: 'learning-plan/challenges-ai-security' }],
    },
  ],

  learningPlanV4Sidebar: [
    { type: 'doc', id: 'learning-plan-v4/overview', label: '🏗️ AI Solution Architect — RAI' },
    { type: 'doc', id: 'learning-plan-v4/weekly-tracker', label: '📊 Weekly Tracker (26 sem)' },
    { type: 'doc', id: 'learning-plan-v4/checkpoints', label: '✅ Checkpoint Gates' },
    { type: 'doc', id: 'learning-plan-v4/evidence-template', label: '🧾 Evidence Template' },
    { type: 'doc', id: 'learning-plan-v4/sources-and-verification', label: '📚 Fuentes y Verificación' },
    { type: 'doc', id: 'learning-plan-v4/methodology-best-practices', label: '🧭 Metodología y Mejores Prácticas' },
    { type: 'doc', id: 'learning-plan-v4/role-competency-map', label: '🎯 Competencias + Benchmark Externo' },
    {
      type: 'category',
      label: 'Fase 1: Fundamentos + AI-103 (Sem 1-4)',
      items: [{ type: 'autogenerated', dirName: 'learning-plan-v4/01-foundation' }],
    },
    {
      type: 'category',
      label: 'Fase 2: Portafolio Técnico — RAG & Agentes (Sem 5-12)',
      items: [{ type: 'autogenerated', dirName: 'learning-plan-v4/02-data-automation' }],
    },
    {
      type: 'category',
      label: 'Fase 3: Arquitectura + Seguridad (Sem 13-16)',
      items: [{ type: 'autogenerated', dirName: 'learning-plan-v4/03-cybersecurity' }],
    },
    {
      type: 'category',
      label: 'Fase 4: Value Realization + Visibilidad (Sem 17-21)',
      items: [{ type: 'autogenerated', dirName: 'learning-plan-v4/04-ai-business' }],
    },
    {
      type: 'category',
      label: 'Fase 5: Entrevistas + Pipeline (Sem 22-26)',
      items: [{ type: 'autogenerated', dirName: 'learning-plan-v4/05-cloud-ai' }],
    },
    {
      type: 'category',
      label: 'Fase 6: Operación Comercial de Carrera (Paralelo)',
      items: [{ type: 'autogenerated', dirName: 'learning-plan-v4/06-career-launch' }],
    },
  ],

  executiveAiLeadershipSidebar: [
    { type: 'doc', id: 'executive-ai-leadership/overview', label: '🎯 Plan Overview' },
    { type: 'doc', id: 'executive-ai-leadership/90-day-execution', label: '⚡ First 90 Days' },
    { type: 'doc', id: 'executive-ai-leadership/value-projects', label: '💼 Value Projects' },
    { type: 'doc', id: 'executive-ai-leadership/certification-roadmap', label: '🎓 Certification Roadmap' },
    { type: 'doc', id: 'executive-ai-leadership/kpi-scorecard', label: '📈 KPI Scorecard' },
    { type: 'doc', id: 'executive-ai-leadership/sources-and-verification', label: '✅ Sources & Verification' },
    {
      type: 'category',
      label: 'Phase 1: Executive AI Foundation',
      items: [{ type: 'autogenerated', dirName: 'executive-ai-leadership/01-foundation' }],
    },
    {
      type: 'category',
      label: 'Phase 2: Commercial AI for Growth',
      items: [{ type: 'autogenerated', dirName: 'executive-ai-leadership/02-commercial-ai' }],
    },
    {
      type: 'category',
      label: 'Phase 3: Governance, Risk, and Contracts',
      items: [{ type: 'autogenerated', dirName: 'executive-ai-leadership/03-governance-risk-contracts' }],
    },
    {
      type: 'category',
      label: 'Phase 4: Scale Across Regions and Portfolio',
      items: [{ type: 'autogenerated', dirName: 'executive-ai-leadership/04-scale-and-leadership' }],
    },
  ],
};

export default sidebars;