// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  foundrySkillSidebar: [
    { type: 'doc', id: 'azure-ai-foundry/overview', label: 'Track Overview' },
    { type: 'doc', id: 'azure-ai-foundry/prerequisites', label: 'Prerequisites & Setup' },
    {
      type: 'category',
      label: 'Platform & Architecture',
      items: [{ type: 'autogenerated', dirName: 'azure-ai-foundry/01-platform' }],
    },
    {
      type: 'category',
      label: 'Agent Service & Types',
      items: [{ type: 'autogenerated', dirName: 'azure-ai-foundry/02-agent-service' }],
    },
    { type: 'doc', id: 'azure-ai-foundry/cheat-sheet', label: 'CLI & SDK Cheat Sheet' },
  ],

  responsibleAiSidebar: [
    { type: 'doc', id: 'responsible-ai/overview', label: 'Track Overview' },
    {
      type: 'category',
      label: 'RAI Standard & Governance',
      items: [{ type: 'autogenerated', dirName: 'responsible-ai/01-rai-standard' }],
    },
    {
      type: 'category',
      label: 'Purview AI Hub & Shadow AI',
      items: [{ type: 'autogenerated', dirName: 'responsible-ai/02-purview-ai-hub' }],
    },
    {
      type: 'category',
      label: 'Fairness & Bias Mitigation',
      items: [{ type: 'autogenerated', dirName: 'responsible-ai/03-content-safety' }],
    },
  ],

  ai102Sidebar: [
    { type: 'doc', id: 'ai-102/overview', label: 'Exam Overview' },
  ],

  az305Sidebar: [
    { type: 'doc', id: 'az-305/overview', label: 'Exam Overview' },
  ],

  sc500Sidebar: [
    { type: 'doc', id: 'sc-500/overview', label: 'Exam Overview' },
  ],

  az104Sidebar: [
    { type: 'doc', id: 'az-104/overview', label: 'Exam Overview' },
  ],

  az700Sidebar: [
    { type: 'doc', id: 'az-700/overview', label: 'Exam Overview' },
  ],

  agenticReliabilitySidebar: [
    { type: 'doc', id: 'agentic-reliability/overview', label: 'Track Overview' },
    {
      type: 'category',
      label: 'The Hallucination Audit',
      items: [{ type: 'autogenerated', dirName: 'agentic-reliability/01-hallucination-audit' }],
    },
    {
      type: 'category',
      label: 'Context Rot at Scale',
      items: [{ type: 'autogenerated', dirName: 'agentic-reliability/02-context-rot' }],
    },
    {
      type: 'category',
      label: 'The Verifiable Orchestrator',
      items: [{ type: 'autogenerated', dirName: 'agentic-reliability/03-verifiable-orchestrator' }],
    },
    {
      type: 'category',
      label: 'Semantic Control',
      items: [{ type: 'autogenerated', dirName: 'agentic-reliability/04-semantic-control' }],
    },
  ],

  claudeArchitectSidebar: [
    { type: 'doc', id: 'claude-architect/overview', label: 'Exam Overview & Study Plan' },
  ],

  resourcesSidebar: [
    { type: 'doc', id: 'resources/overview', label: 'Resources Hub' },
    { type: 'doc', id: 'resources/tools', label: '🛠️ Tools' },
    { type: 'doc', id: 'resources/articles', label: '📰 Articles' },
    { type: 'doc', id: 'resources/learning', label: '📚 Learning' },
  ],

  learningPlanSidebar: [
    { type: 'doc', id: 'learning-plan/overview', label: '🎯 Plan Overview' },
    {
      type: 'category',
      label: 'Fase 1: Fundamentos (Semanas 1-4)',
      items: [{ type: 'autogenerated', dirName: 'learning-plan/01-foundation' }],
    },
    {
      type: 'category',
      label: 'Fase 2: Datos & Automatización (Semanas 5-8)',
      items: [{ type: 'autogenerated', dirName: 'learning-plan/02-data-automation' }],
    },
    {
      type: 'category',
      label: 'Fase 3: Ciberseguridad (Semanas 9-12)',
      items: [{ type: 'autogenerated', dirName: 'learning-plan/03-cybersecurity' }],
    },
    {
      type: 'category',
      label: 'Fase 4: AI para Negocios (Semanas 13-20)',
      items: [{ type: 'autogenerated', dirName: 'learning-plan/04-ai-business' }],
    },
    {
      type: 'category',
      label: 'Fase 5: Cloud + AI (Semanas 21-28)',
      items: [{ type: 'autogenerated', dirName: 'learning-plan/05-cloud-ai' }],
    },
    {
      type: 'category',
      label: 'Fase 6: Lanzamiento (Semanas 29-36)',
      items: [{ type: 'autogenerated', dirName: 'learning-plan/06-career-launch' }],
    },
  ],
};

export default sidebars;
